- name: Install and Configure Nginx
  hosts: server
  become: yes
  vars:
    welcome_message: "Hello Guys 👋"
    company: "DevOps Academy"
    trainer: "Kiran"
    course: "Ansible for Beginners"
    environment: "Production"

  tasks:

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Enable nginx
      service:
        name: nginx
        enabled: yes

    - name: Start nginx
      service:
        name: nginx
        state: started

    - name: copy file
      copy: 
        src: index.html
        dest: /var/www/html/index.html

