- name: secrets-playbook
  hosts: server
  become: yes
  
  vars_files:
    - secrets.yml

  tasks:
    - name: secrets-task
      debug: 
        msg: "db username is{{db_username}}"
      no_log: true  
    - name: display-password
      debug:
        msg: "db password is {{db_password}}"
      no_log: true
